version: "3"
services:
  grav:
    build: ./
    ports:
      - 8000:80
    volumes:
      - ./themes/yunohost-docs:/var/www/html/user/themes/yunohost-docs
      - ./config:/var/www/html/user/config
      - ./pages:/var/www/html/user/pages
      - ./images:/var/www/html/user/images
#  tntsearch:
#    restart: "no"
#    build: ./
#    volumes:
#      - ./config:/var/www/html/user/config
#      - ./pages:/var/www/html/user/pages
#    command: bin/plugin tntsearch index
