// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)


const redirects_from_grav = [
    { from: '/admin_guide',                             to: '/admin/admin', },
    { from: '/admin_interface',                         to: '/admin/', },
    { from: '/apps_overview',                           to: '/admin/apps/', },
    { from: '/custom_apps',                             to: '/admin/apps/custom_apps', },
    { from: '/ssh',                                     to: '/admin/command_line', },
    { from: '/domains',                                 to: '/admin/domains/', },
    { from: '/certificate',                             to: '/admin/domains/certificate', },
    { from: '/email',                                   to: '/admin/email', },
    { from: '/guidelines',                              to: '/admin/guidelines', },
    { from: '/update',                                  to: '/admin/upgrade/', },
    { from: '/bullseye_bookworm_migration',             to: '/admin/upgrade/bullseye_bookworm/', },
    { from: '/bookworm_migration_issues_faq',           to: '/admin/upgrade/bullseye_bookworm/issues_faq', },
    { from: '/buster_bullseye_migration',               to: '/admin/upgrade/buster_bullseye_migration', },
    { from: '/users',                                   to: '/admin/users/', },
    { from: '/groups_and_permissions',                  to: '/admin/users/groups_and_permissions', },
    { from: '/backup',                                  to: '/admin/backups/', },
    { from: '/backup/prevent_hardware_failure',         to: '/admin/backups/avoid_hardware_failure', },
    { from: '/backup/backup_methods',                   to: '/admin/backups/backup_methods', },
    { from: '/backup/clone_filesystem',                 to: '/admin/backups/clone_filesystem', },
    { from: '/backup/custom_backup_methods',            to: '/admin/backups/custom_backup_methods', },
    { from: '/backup_strategies',                       to: '/admin/backups/evaluate', },
    { from: '/backup/include_exclude_files',            to: '/admin/backups/include_exclude_files', },
    { from: '/backup/migrate_or_merge_servers',         to: '/admin/backups/migrate_or_merge_servers', },
    { from: '/troubleshooting',                         to: '/admin/troubleshooting/', },
    { from: '/blacklist_forms',                         to: '/admin/troubleshooting/blacklist_forms', },
    { from: '/change_admin_password',                   to: '/admin/troubleshooting/change_admin_password', },
    { from: '/cleanup',                                 to: '/admin/troubleshooting/cleanup', },
    { from: '/fail2ban',                                to: '/admin/troubleshooting/fail2ban', },
    { from: '/ipv6',                                    to: '/admin/troubleshooting/ipv6', },
    { from: '/noaccess',                                to: '/admin/troubleshooting/noaccess', },
    { from: '/certificate_custom',                      to: '/admin/tutorials/certificate_custom', },
    { from: '/dns_dynamicip',                           to: '/admin/tutorials/domains/dns_dynamicip', },
    { from: '/dns_local_network',                       to: '/admin/tutorials/domains/dns_local_network', },
    { from: '/dns_nohost_me',                           to: '/admin/tutorials/domains/dns_nohost_me', },
    { from: '/dns_subdomains',                          to: '/admin/tutorials/domains/dns_subdomains', },
    { from: '/email_configure_relay',                   to: '/admin/tutorials/email_configure_relay', },
    { from: '/external_storage',                        to: '/admin/tutorials/external_storage', },
    { from: '/filezilla',                               to: '/admin/tutorials/filezilla', },
    { from: '/moving_app_folder',                       to: '/admin/tutorials/moving_app_folder', },
    { from: '/security',                                to: '/admin/tutorials/security', },
    { from: '/sftp_on_apps',                            to: '/admin/tutorials/sftp_on_apps', },
    { from: '/theming',                                 to: '/admin/tutorials/theming', },
    { from: '/torhiddenservice',                        to: '/admin/tutorials/torhiddenservice', },
    { from: '/admindoc',                                to: '/category/administration-guide', },
    { from: '/advanced_packagers',                      to: '/category/advanced', },
    { from: '/community',                               to: '/category/community', },
    { from: '/asking_for_help_efficiently',             to: '/community/asking_for_help_efficiently', },
    { from: '/chat_rooms',                              to: '/community/chat_rooms', },
    { from: '/faq',                                     to: '/community/faq', },
    { from: '/help',                                    to: '/community/help', },
    { from: '/press_kit',                               to: '/community/press_kit', },
    { from: '/project_budget',                          to: '/community/project_budget', },
    { from: '/security_team',                           to: '/community/security_team', },
    { from: '/sponsors_partners',                       to: '/community/sponsors_partners', },
    { from: '/terms_of_services',                       to: '/community/terms_of_services', },
    { from: '/contributordoc',                          to: '/contribute/', },
    { from: '/dev',                                     to: '/contribute/dev/', },
    { from: '/dev/forms',                               to: '/contribute/dev/forms', },
    { from: '/dev/maindomain',                          to: '/contribute/dev/maindomain', },
    { from: '/packaging_apps',                          to: '/contribute/packaging_apps/', },
    { from: '/packaging_config_panels',                 to: '/contribute/packaging_apps/advanced/config_panels', },
    { from: '/packaging_apps_hooks',                    to: '/contribute/packaging_apps/advanced/packaging_apps_hooks', },
    { from: '/packaging_v2',                            to: '/contribute/packaging_apps/advanced/packaging_v2', },
    { from: '/packaging_sso_ldap_integration',          to: '/contribute/packaging_apps/advanced/sso_ldap_integration', },
    { from: '/packaging_app_doc',                       to: '/contribute/packaging_apps/doc', },
    { from: '/packaging_manifest',                      to: '/contribute/packaging_apps/manifest/', },
    { from: '/packaging_apps_resources',                to: '/contribute/packaging_apps/manifest/app_resources', },
    { from: '/packaging_policy',                        to: '/contribute/packaging_apps/policy', },
    { from: '/packaging_publishing',                    to: '/contribute/packaging_apps/publishing', },
    { from: '/packaging_apps_git',                      to: '/contribute/packaging_apps/resources/packaging_apps_git', },
    { from: '/packaging_apps_virtualbox',               to: '/contribute/packaging_apps/resources/packaging_apps_virtualbox', },
    { from: '/packaging_scripts',                       to: '/contribute/packaging_apps/scripts/', },
    { from: '/packaging_apps_helpers',                  to: '/contribute/packaging_apps/scripts/packaging_app_scripts_helpers', },
    { from: '/packaging_apps_helpers_v2.1',             to: '/contribute/packaging_apps/scripts/packaging_app_scripts_helpers_v21', },
    { from: '/shell_variables_scope',                   to: '/contribute/packaging_apps/scripts/shell_variables_scope', },
    { from: '/packaging_testing',                       to: '/contribute/packaging_apps/testing', },
    { from: '/write_documentation',                     to: '/contribute/write_documentation/', },
    { from: '/doc_writing_guide',                       to: '/contribute/write_documentation/apps_documentation', },
    { from: '/doc_use_git',                             to: '/contribute/write_documentation/git', },
    { from: '/doc_markdown_guide',                      to: '/contribute/write_documentation/markdown_guide', },
    { from: '/howtohostyourself',                       to: '/install/', },
    { from: '/install_on_top_of_debian',                to: '/install/install_on/on_top_of_debian', },
    { from: '/dns_config',                              to: '/install/post_install/dns_config', },
    { from: '/finding_the_local_ip',                    to: '/install/post_install/finding_the_local_ip', },
    { from: '/isp_box_config',                          to: '/install/post_install/isp_box_config', },
    { from: '/providers/isp',                           to: '/install/providers/isp/', },
    { from: '/providers/isp/free',                      to: '/install/providers/isp/free', },
    { from: '/providers/isp/orange',                    to: '/install/providers/isp/orange', },
    { from: '/providers/isp/sfr',                       to: '/install/providers/isp/sfr', },
    { from: '/providers/registrar',                     to: '/install/providers/registrar/', },
    { from: '/providers/registrar/gandi/autodns',       to: '/install/providers/registrar/gandi', },
    { from: '/providers/registrar/namecheap/autodns',   to: '/install/providers/registrar/namecheap', },
    { from: '/providers/registrar/ovh/autodns',         to: '/install/providers/registrar/ovh/autodns', },
    { from: '/providers/registrar/ovh/manualdns',       to: '/install/providers/registrar/ovh/manualdns', },
    { from: '/providers/server',                        to: '/install/providers/servers', },
    { from: '/providers/vpn',                           to: '/install/providers/vpn/', },
    { from: '/vpn_advantage',                           to: '/install/providers/vpn/vpn_advantage', },
    { from: '/selfhosting',                             to: '/overview/self_hosting', },
    { from: '/try',                                     to: '/overview/try_yunohost', },
    { from: '/whatsyunohost',                           to: '/overview/what_is_yunohost', },
    { from: '/email_configure_client',                  to: '/user/email_configure_client', },
    { from: '/email_migration',                         to: '/user/email_migration', },
]


/** @type {import('@docusaurus/plugin-client-redirects').Options} */

const redirects = {
    redirects: redirects_from_grav.concat([]),
};

export default redirects;
