import { Options } from '@docusaurus/plugin-client-redirects';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const redirects_from_grav: Array<{ from: string; to: string }> = [
    { from: '/admindoc',                                to: '/admin', },
    { from: '/admin_interface',                         to: '/admin/webadmin', },
    { from: '/apps_overview',                           to: '/admin/apps/', },
    { from: '/custom_apps',                             to: '/admin/apps/custom_apps', },
    { from: '/ssh',                                     to: '/admin/command_line', },
    { from: '/domains',                                 to: '/admin/domains/', },
    { from: '/certificate',                             to: '/admin/domains/certificate', },
    { from: '/email',                                   to: '/admin/email', },
    { from: '/email_configure_client',                  to: '/admin/email/clients', },
    { from: '/email_migration',                         to: '/admin/email/migration', },
    { from: '/guidelines',                              to: '/admin/get_started/guidelines', },
    { from: '/update',                                  to: '/admin/upgrade/', },
    { from: '/buster_bullseye_migration',               to: '/admin/upgrade/11.0-bullseye', },
    { from: '/bullseye_bookworm_migration',             to: '/admin/upgrade/12.0-bookworm/', },
    { from: '/bookworm_migration_issues_faq',           to: '/admin/upgrade/12.0-bookworm/issues_faq', },
    { from: '/users',                                   to: '/admin/users/', },
    { from: '/groups_and_permissions',                  to: '/admin/users/groups_and_permissions', },
    { from: '/backup',                                  to: '/admin/backups/', },
    { from: '/backup/prevent_hardware_failure',         to: '/admin/backups/avoid_hardware_failure', },
    { from: '/backup/backup_methods',                   to: '/admin/backups/backup_methods', },
    { from: '/backup/clone_filesystem',                 to: '/admin/backups/clone_filesystem', },
    { from: '/backup/custom_backup_methods',            to: '/admin/backups/custom_backup_methods', },
    { from: '/backup_strategies',                       to: '/admin/backups/evaluate', },
    { from: '/backup/include_exclude_files',            to: '/admin/backups/include_exclude_files', },
    { from: '/backup/migrate_or_merge_servers',         to: '/admin/backups/migrate_or_merge_servers', },
    { from: '/troubleshooting',                         to: '/admin/troubleshooting/', },
    { from: '/blacklist_forms',                         to: '/admin/troubleshooting/blacklist_forms', },
    { from: '/change_admin_password',                   to: '/admin/troubleshooting/change_admin_password', },
    { from: '/cleanup',                                 to: '/admin/troubleshooting/cleanup', },
    { from: '/fail2ban',                                to: '/admin/troubleshooting/fail2ban', },
    { from: '/ipv6',                                    to: '/admin/troubleshooting/ipv6', },
    { from: '/noaccess',                                to: '/admin/troubleshooting/noaccess', },
    { from: '/certificate_custom',                      to: '/admin/tutorials/certificate_custom', },
    { from: '/dns_dynamicip',                           to: '/admin/tutorials/domains/dns_dynamicip', },
    { from: '/dns_local_network',                       to: '/admin/tutorials/domains/dns_local_network', },
    { from: '/dns_nohost_me',                           to: '/admin/tutorials/domains/dns_nohost_me', },
    { from: '/dns_subdomains',                          to: '/admin/tutorials/domains/dns_subdomains', },
    { from: '/email_configure_relay',                   to: '/admin/tutorials/email_configure_relay', },
    { from: '/external_storage',                        to: '/admin/tutorials/external_storage', },
    { from: '/filezilla',                               to: '/admin/tutorials/filezilla', },
    { from: '/moving_app_folder',                       to: '/admin/tutorials/moving_app_folder', },
    { from: '/security',                                to: '/admin/tutorials/security', },
    { from: '/sftp_on_apps',                            to: '/admin/tutorials/sftp_on_apps', },
    { from: '/theming',                                 to: '/admin/tutorials/theming', },
    { from: '/torhiddenservice',                        to: '/admin/tutorials/torhiddenservice', },
    { from: '/howtohostyourself',                       to: '/admin/get_started/methods', },
    { from: '/install',                                 to: '/admin/get_started/install_on', },
    { from: '/install_on_top_of_debian',                to: '/admin/get_started/install_on/on_top_of_debian', },
    { from: '/dns_config',                              to: '/admin/get_started/post_install/dns_config', },
    { from: '/dns',                                     to: '/admin/get_started/post_install/dns_config', },
    { from: '/finding_the_local_ip',                    to: '/admin/get_started/post_install/find_ip', },
    { from: '/isp_box_config',                          to: '/admin/get_started/post_install/port_forwarding', },
    { from: '/selfhosting',                             to: '/admin/about_self_hosting', },
    { from: '/providers/isp',                           to: '/admin/get_started/providers/isp/', },
    { from: '/providers/isp/free',                      to: '/admin/get_started/providers/isp/free', },
    { from: '/providers/isp/orange',                    to: '/admin/get_started/providers/isp/orange', },
    { from: '/providers/isp/sfr',                       to: '/admin/get_started/providers/isp/sfr', },
    { from: '/providers/registrar',                     to: '/admin/get_started/providers/registrar/', },
    { from: '/providers/registrar/gandi/autodns',       to: '/admin/get_started/providers/registrar/gandi', },
    { from: '/providers/registrar/namecheap/autodns',   to: '/admin/get_started/providers/registrar/namecheap', },
    { from: '/providers/registrar/ovh/autodns',         to: '/admin/get_started/providers/registrar/ovh/autodns', },
    { from: '/providers/registrar/ovh/manualdns',       to: '/admin/get_started/providers/registrar/ovh/manualdns', },

    { from: '/registar_api_ovh',                        to: '/admin/get_started/providers/registrar/ovh/autodns', }, 
    { from: '/registar_api_gandi',                      to: '/admin/get_started/providers/registrar/gandi', }, 
    { from: '/registar_api_namecheap',                  to: '/admin/get_started/providers/registrar/namecheap', }, 

    { from: '/providers/server',                        to: '/admin/get_started/providers/servers', },
    { from: '/providers/vpn',                           to: '/admin/get_started/providers/vpn/', },
    { from: '/vpn_advantage',                           to: '/admin/get_started/providers/vpn/vpn_advantage', },
    { from: '/try',                                     to: '/admin/what_is_yunohost/demo', },
    { from: '/whatsyunohost',                           to: '/admin/what_is_yunohost', },
    { from: '/admin_guide',                             to: '/admin/what_is_yunohost/structure', },

    { from: '/asking_for_help_efficiently',             to: '/community/help', },
    { from: '/chat_rooms',                              to: '/community/chat_rooms', },
    { from: '/faq',                                     to: '/community/faq', },
    { from: '/help',                                    to: '/community/help', },
    { from: '/press_kit',                               to: '/community/press_kit', },
    { from: '/project_budget',                          to: '/community/project_budget', },
    { from: '/security_team',                           to: '/community/security_team', },
    { from: '/sponsors_partners',                       to: '/community/sponsors_partners', },
    { from: '/terms_of_services',                       to: '/community/terms_of_services', },

    { from: '/contributordoc',                          to: '/dev/', },
    { from: '/contribute',                              to: '/dev/', },    
    { from: '/dev/forms',                               to: '/dev/core/forms', },
    { from: '/dev/maindomain',                          to: '/dev/core/maindomain', },
    { from: '/write_documentation',                     to: '/dev/doc/', },
    { from: '/doc_writing_guide',                       to: '/dev/doc/apps_documentation', },
    { from: '/doc_use_git',                             to: '/dev/doc/git', },
    { from: '/doc_markdown_guide',                      to: '/dev/doc/markdown_guide', },
    { from: '/docs',                                     to: '/', },

    { from: '/packaging_apps',                          to: '/packaging/', },
    { from: '/advanced_packagers',                      to: '/packaging/advanced', },
    { from: '/packaging_config_panels',                 to: '/packaging/advanced/config_panels', },
    { from: '/packaging_apps_hooks',                    to: '/packaging/advanced/hooks', },
    { from: '/packaging_v2',                            to: '/packaging/advanced/packaging_v2', },
    { from: '/packaging_sso_ldap_integration',          to: '/packaging/advanced/sso_ldap_integration', },
    { from: '/packaging_app_doc',                       to: '/packaging/doc', },
    { from: '/packaging_manifest',                      to: '/packaging/manifest/', },
    { from: '/packaging_apps_resources',                to: '/packaging/manifest/resources', },
    { from: '/packaging_policy',                        to: '/packaging/policy', },
    { from: '/packaging_publishing',                    to: '/packaging/publish', },
    { from: '/packaging_apps_git',                      to: '/packaging/resources/packaging_apps_git', },
    { from: '/packaging_apps_virtualbox',               to: '/packaging/resources/packaging_apps_virtualbox', },
    { from: '/packaging_scripts',                       to: '/packaging/scripts/', },
    { from: '/packaging_apps_helpers',                  to: '/packaging/scripts/helpers_v2.0', },
    { from: '/packaging_apps_helpers_v2.1',             to: '/packaging/scripts/helpers_v2.1', },
    { from: '/shell_variables_scope',                   to: '/packaging/scripts/shell_variables_scope', },
    { from: '/packaging_testing',                       to: '/packaging/test', },
];

const en_redirects_from_grav: Array<{ from: string; to: string }> = redirects_from_grav.map(
  item => ({ from: '/en' + item.from, to: item.to})
);

const redirects: Options = {
    redirects: [...redirects_from_grav, ...en_redirects_from_grav],
};

export default redirects;
