import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // user: [
  //   {type: 'autogenerated', dirName: 'user'},
  // ],
  community: [
    {type: 'autogenerated', dirName: 'community'}
  ],
  admin: [
    {type: 'autogenerated', dirName: 'admin'},
  ],
  devpackaging: [
    {type: 'autogenerated', dirName: 'dev'},
    {
      type: "category",
      label: "Packaging applications",
      link: {"type": "doc", id: "packaging/index"},
      items: [{type: 'autogenerated', dirName: 'packaging'}]
    },
  ],
};

export default sidebars;
