title: 'YunoHost Documentation'
default_lang: en
author:
  name: YunoHost
  email: yunohost@yunohost.org
taxonomies:
  - category
  - tag
metadata:
  description: 'YunoHost Documentation'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
