name: Set up translations tools

runs:
  using: "composite"
  steps:
  - name: Set up Python
    uses: actions/setup-python@v5

  - name: Install perl dependencies (for po4a)
    shell: bash
    run: |
      sudo apt install -y po4a

  - name: Tweak enabled locales according to Weblate statistics (keep langs with >= 5% translated)
    shell: bash
    run: scripts/update_linguas.sh
