name: Check and build Docusaurus doc

inputs:
  base_url:
    description: Base URL to pass to Docusaurus
    required: true
    default: /

runs:
  using: "composite"
  steps:
  - name: Set up Node
    uses: actions/setup-node@v4
    with:
      node-version: lts/*

  - name: Installation
    shell: bash
    run: npm ci

  - name: Build docs
    env:
      BASE_URL: "${{ inputs.base_url }}"
    shell: bash
    run: |
      echo "Using baseUrl=$BASE_URL"
      npm run update-ui-translations
      npm run build
