name: Auto-regen the .pot used as source for translations (po4a/Weblate)

on:
  push:
    branches: [ "main" ]

jobs:
  auto_regen_pot:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install translation tools
        uses: ./.github/actions/po4a

      - name: Regenerate the .pot file
        shell: bash
        run: ./scripts/po4a.py regen_pot

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🌐 ${{ github.workflow }}"
