name: Check for dead links

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install python-frontmatter
    - name: Check for dead links
      run: tests/dead_links.py
