name: Lint Markdown

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: .markdownlint.json
        globs: '**/*.md'
